### ISSUE TITLE
Config error for Assetic Bundle

### ISSUE THREAD

**Issue by iknowfoobar** [Kunstmaan/KunstmaanBundlesCMS#1036]
I can see that in previous installs of the bundles (<3.5) that the config for the assetic bundle looked like this:

```yml
assetic:
    use_controller: "%use_assetic_controller%"
    node: /path/to/node
    filters:
        uglifyjs2:
            bin: /path/to/uglifyjs
            compress: true
        uglifycss:
            bin: /path/to/uglifycss
```

However in a fresh install of 3.5 the config has been changed to 

```yml
assetic:
    use_controller: "%use_assetic_controller%"
    node: /path/to/node
    filters:
        uglifyjs2:
            bin: /path/to/uglifyjs
            compress: true
        uglifycss: /path/to/uglifycss
```

The config for uglifycss is now a string rather than an array. This results in a fatal error when trying to run assetic:dump

```bash
Invalid configuration for path "assetic.filters.uglifycss": The assetic.filters config "\/usr\/local\/bin\/uglifycss" must be either nu  
  ll or an array. 
```

Changing the config back to how it was previously fixes this problem for me.
