### ISSUE TITLE
Undefined index: client_id

### ISSUE THREAD

**Issue by w3q** [Kunstmaan/KunstmaanBundlesCMS#1124]
Hi,

I found one problem and don't really know why it just stopped working.

I have my KunstmaanBundlesCMS working. I've been doing some customization, part of it was to composer install "jms/i18n-routing-bundle": "dev-master".

After composer update, I've started to get the error message:

<img width="1280" alt="snimka obrazovky 2016-04-22 o 11 51 47" src="https://cloud.githubusercontent.com/assets/1138670/14738203/a03541d2-0880-11e6-9f54-bcc5f0646625.png">

Now Im not able even to remove the bundle from composer, since composer remove will return the same error just in command line.

I have no idea why it did happened after installing the i18n-routing-bundle, cause it looks like it has something to do with OAuth for the admin?

Thank you a lot.

**Comment by ronaldtb** [comment]
I just ran into the same problem. A workaround seems to be to add the `google_signin` configuration to your config.yml. This probleem seems to be related to #806 and #1119.

```yaml
kunstmaan_admin:
    admin_password: -adminpwd-
    dashboard_route: 'kunstmaan_dashboard'
    google_signin:
        enabled: false
        client_id: ''
        client_secret: ''
```
