### ISSUE TITLE
[SearchBundle] There is no polish language analyzer

### ISSUE THREAD

**Issue by BatcherX** [Kunstmaan/KunstmaanBundlesCMS#1130]
Can you add polish please?

**Comment by mlebkowski** [comment]
Do you need to update the framework for that? I use polish language without any problems, this is a part of my `config.yml`:

```yml
kunstmaan_search:
    analyzer_languages:
        pl: { analyzer: 'polish' }
        en: { analyzer: 'english' }
        de: { analyzer: 'german' }
```
