### ISSUE TITLE
css : 404 on default bundle

### ISSUE THREAD

**Issue by ArthurJam** [Kunstmaan/KunstmaanBundlesCMS#1356]
Hello,

I dont understand how i can edit the css files and how i can load them.
By default, i have a 404 error from frontend/css/style.min.css

Do i missed something ?
Thanks.

**Comment by ArthurJam** [comment]
I found this workaround : 

In views\Layout\_css.html.twig i change the content by this : 

```
{% block css %}
    {% stylesheets "@MyWebsiteBundle/Resources/ui/scss/style.scss" output="MyWebsiteBundleAssets/css/style.min.css" filter="scss" %}
    <link href="{{ asset_url }}" type="text/css" rel="stylesheet" media="screen"/>
    {% endstylesheets %}
{% endblock %}
```

In app/config/config.yml in assetic section  : 

```
assetic:
    bundles: [MyWebsiteBundle]
    filters:
        scss:
            load_paths:
                - "%kernel.root_dir%/.."
```

The execute a cache:clear and assetic:dump

I think i misunderstood something (including how to write in english 😄 ).
