### ISSUE TITLE
How to add tab with kunstmaan_admin.adaptSimpleForm Event

### ISSUE THREAD

**Issue by ismaserrano** [Kunstmaan/KunstmaanBundlesCMS#1480]
I've trying to add a tab to admin form without success.
I'm defining a service trying to inject adaptSimpleForm with:

```
companymybundle.adaptSimpleForm:
        class: Company\MyBundle\Event\AdaptSimpleFormEvent
        arguments: []
        tags:
            - { name: kernel.event_listener, event: kunstmaan_admin.adaptSimpleForm, method: onAdaptSimpleFormEvent }
```

but... I don't have access, I can't find it adaptSimpleForm service. What is the correct way to add a tab?
Thank you!

**Comment by Devolicious** [comment]
Hi @ismaserrano, 

There is no `adaptSimpleFormService`. You service definition that you made is a good start. You should inject the `@form.factory` and add it as a property in your class. The next thing that you need to do is to add the following to you eventlistener class:

```php
public function onAdaptSimpleFormEvent(AdaptSimpleFormEvent $event)
{
    $form = $event->getFormType();
    if ($form == SomeFormType::class) {
        $data = $event->getData();
        $tabPane = new TabPane(
            'my_custom_tabpane',
            $event->getRequest(),
            $this->formFactory // this is why you need to inject the @form.factory
        );

        $widget = new FormWidget();
        $widget->addType('My tabbed form', $form, $data);
        $tabPane->addTab(new Tab('My custom tab', $mappingWidget), 1);

        ...

        $tabPane->buildForm();
        $event->setTabPane($tabPane);
    }
}
```

Happy coding!

**Comment by ismaserrano** [comment]
Okay, thank you, looks good, I've:

```
companymybundlebundle.adaptSimpleForm:
        class: Company\MyBundle\Event\AdaptSimpleFormEvent
        arguments: ["@form.factory"]
        tags:
            - { name: kernel.event_listener, event: kunstmaan_admin.adaptSimpleForm, method: onAdaptSimpleFormEvent }
```

And in Company\MyBundle\Event\AdaptSimpleFormEvent.php:

```
use Kunstmaan\AdminBundle\Helper\FormWidgets\Tabs\TabPane;
use Symfony\Component\EventDispatcher\Event;
use Symfony\Component\Form\FormFactory;
use Kunstmaan\AdminBundle\Helper\FormWidgets\FormWidget;
use Kunstmaan\AdminBundle\Helper\FormWidgets\Tabs\Tab;

/**
 * Class AdaptSimpleFormEvent
 * @package Company\MyBundle\Event
 */
class AdaptSimpleFormEvent extends Event
{

    protected $formFactory;

    public function __construct(FormFactory $formFactory)
    {
        $this->formFactory = $formFactory;
    }

    public function onAdaptSimpleFormEvent(AdaptSimpleFormEvent $event)
    {
        $form = $event->getFormType();
            $data = $event->getData();
            $tabPane = new TabPane(
                'my_custom_tabpane',
                $event->getRequest(),
                $this->formFactory // this is why you need to inject the @form.factory
            );

            $widget = new FormWidget();
            $widget->addType('My tabbed form', $form, $data);
            $tabPane->addTab(new Tab('My custom tab', $widget), 1);

            $tabPane->buildForm();
            $event->setTabPane($tabPane);
    }
.
.
.
```

but nothing happens... looks like the service injection declaration is wrong...

**Comment by Devolicious** [comment]
The definition seems fine. Where are you trying to use this? Because the `kunstmaan_admin.adaptSimpleForm` event will only trigger on an adminlist. Is that were you are trying to add tabs or is it on a page?

**Comment by ismaserrano** [comment]
Is in the detail form inside a node, adding tab with Content, Menu, Seo...
I found a solution creating a new bundle and creating a NodeListener with (I think not is a global solution, what do you think?):

```
/**
     * @var EntityManager
     */
    private $em;

    /**
     * @param EntityManager $em
     */
    public function __construct(EntityManager $em)
    {
        $this->em = $em;
    }

    /**
     * @param AdaptFormEvent $event
     */
    public function adaptForm(AdaptFormEvent $event)
    {
        if ($event->getPage() instanceof HasNodeInterface && !$event->getPage()->isStructureNode()) {
            /* @var Ga $ga */
            $ga = $this->em->getRepository('CompanyGaBundle:Ga')->findOrCreateFor($event->getPage());

            $gaWidget = new FormWidget();
            $gaWidget->addType('ga', new GaType(), $ga);
            $event->getTabPane()->addTab(new Tab('Google Analytics', $gaWidget));
        }
    }
```

and the service declaration:

```
companymybundle_ga.node.listener:
        class: Company\GaBundle\EventListener\NodeListener
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: kernel.event_listener, event: kunstmaan_node.adaptForm, method: adaptForm }
```

and other Twig extension for call methods from template, create the form type...

I hope it helps other people.

Thank you for your support!
