### ISSUE TITLE
[SearchBundle] Populate command failing

### ISSUE THREAD

**Issue by wesleylancel** [Kunstmaan/KunstmaanBundlesCMS#1704]
After some recent changes in the SearchBundle I'm running in to some issues, first when executing `kuma:search:populate full`:

```
[Symfony\Component\Console\Exception\LogicException]
  Cannot retrieve helper "question" because there is no HelperSet defined. Did you forget to add your command to the application or to set the application on the command using the setApplication() method? You can also set the HelperSet directly using the setHelperSet() method.
```

When I run the setup command itsself, it will ask about unavailable language analyzers, however I did configure those:

```
kunstmaan_search:
    analyzer_languages:
        nl_BE: { analyzer: 'dutch' }
        nl_NL: { analyzer: 'dutch' }
        fr_BE: { analyzer: 'french' }
```
