### ISSUE TITLE
Redirect loop on /[locale]/admin/change-password

### ISSUE THREAD

**Issue by jazzzpor** [Kunstmaan/KunstmaanBundlesCMS#1975]
Steps to reproduce:

1. Following the guide on http://kunstmaanbundlescms.readthedocs.io/en/latest/installation/ 
2. Log in on /nl/admin and enter the admin username and password that was generated during `bin/console kuma:generate:default-site`
3. Redirect loop occurs at /nl/admin/change-password

Edit:
Here are my relevant parameters:

```
parameters:
    defaultlocale: nl
    locale: nl
    multilanguage: true
    requiredlocales: nl
```

**Comment by mwoynarski** [comment]
I've found/fixed the issue and submitted a pull request:
https://github.com/Kunstmaan/KunstmaanBundlesCMS/pull/1985

In the meantime, you can resolve the issue locally by overriding two routes:

```
KunstmaanAdminBundle_user_change_password:
    path: /%kunstmaan_admin.admin_prefix%/settings/users/{id}/edit
    defaults: { _controller: fos_user.change_password.controller:changePasswordAction }
    methods: [GET, POST]
```

```
fos_user_change_password:
    path: /%kunstmaan_admin.admin_prefix%/profile/change-password
    defaults: { _controller: fos_user.change_password.controller:changePasswordAction }
    methods: [GET, POST]
```
