### ISSUE TITLE
[PagepartBundle] Translate PagePart name

### ISSUE THREAD

**Issue by poveu** [Kunstmaan/KunstmaanBundlesCMS#2519]
In current situation, when we want to add any Pagepart to the page, we see the list of Pageparts with their not-translated name (like "ImageButton", "ImagesGallery", "IntroText") etc.
It's better to translate the names just like anything else in the CMS.

We can edit **/config/kunstmaancms/pageparts/\*\*\*.yml** and add translation string to the names of Pageparts this way, for example:

```
kunstmaan_page_part:
    pageparts:
        main:
            name: 'Main'
            context: main
            types:
                - { name: 'pageparts.introText', class: App\Entity\PageParts\IntroTextPagePart, preview: 'frontend/img/pp-previews/introtext-pp.svg' }
```

And then specify the translation for "**pageparts.introText**".

To this very moment everything's just fine - the names are displayed correctly with corresponding translation.

However this breaks the top "Pagepart search" function, because it doesn't get the translated strings (like "Intro text") but the exact string we have put into .yml file (in this case it's exactly "pageparts.introText") - this means we cannot search by the translated name.

For now, I have a not-so-pretty workaround, overriding **vendor/kunstmaan/pagepart-bundle/Resources/views/PagePartAdminTwigExtension/modal.html.twig**
Instead of:
```
data-pp-types="{{ pagepartadmin.possiblePagePartTypes|json_encode() }}"
```
I have:
```
data-pp-types="{{ pagepartadmin.possiblePagePartTypes|map(pp => {'name': pp.name|trans, 'class': pp.class, 'preview': pp.preview })|json_encode(constant('JSON_UNESCAPED_UNICODE')) }}"
```
And instead of:
```
data-pp-name="{{ pagePartType.name }}"
```
I have:
```
data-pp-name="{{ pagePartType.name|trans }}"
```

This way JS function (initSearch) gets proper string to search in and everythings works fine. 

However this is just a workaround, translating shouldn't be done by mapping the whole array in twig file - that's why I'm creating this issue as an idea for the future releases.
