### ISSUE TITLE
PagesConfiguration initialised with empty configuration

### ISSUE THREAD

**Issue by henrypenny** [Kunstmaan/KunstmaanBundlesCMS#2591]
I've recently upgraded a couple of older sites to Symfony 4.x and Kunstmaan Cms along with it.

I've noticed I can't add a HomePage if I have no nodes.

I added a break point in:
`Kunstmaan\NodeBundle\Helper\PagesConfiguration::__construct(array $configuration)`

This seems to consistently receive an empty array for it's configuration.

Also, `App\Entity\Pages\HomePage::getPossibleChildTypes()` never seems to be called. Either via loading the admin nodes page. Or via clearing the cache.

I understood this was the way in which Kunstmaan built up the structure of page nesting possibilities. 

As a work around I've addedsome configuration here:

`config/packages/kunstmaan_node.yaml`

```
kunstmaan_node:
    lock:
        enabled: true
    pages:
        App\Entity\Pages\HomePage:
            name: 'Home Page'
            allowed_children:
                - 'App\Entity\Pages\ContentPage'
        App\Entity\Pages\ContentPage:
            name: 'Content Page'

```

This causes a `$configuration` variable to be passed to the constructor of `PagesConfiguration` and allows me to add a Home Page.
Will I need to add to the configuration above every time I add a new page type going forward?
