### ISSUE TITLE
[AdminBundle] PagePart builder with "pagelimit" configuration

### ISSUE THREAD

**Issue by sfi-fgarnier** [Kunstmaan/KunstmaanBundlesCMS#2768]
```yaml
kunstmaan_page_part:
    pageparts:
        main:
            name: Main
            context: main
            types:
                - { name: Header, class: App\Entity\PageParts\HeaderPagePart, pagelimit: 2 }
                - { name: Image, class: App\Entity\PageParts\ImagePagePart }
                - { name: Text, class: App\Entity\PageParts\TextPagePart }
                - { name: Video, class: App\Entity\PageParts\VideoPagePart }
```

You can add more than 2 HeaderPagePart before saving form.
There is no JS behaviour (show/hide "Add a PagePart" button) and no PHP validation with error flash message after submitting page.

Can you fix this please ?
