### ISSUE TITLE
[AdminBundle] `SimpleMenuAdaptor` allows adding menu items via configuration

### ISSUE THREAD

**Issue by mlebkowski** [Kunstmaan/KunstmaanBundlesCMS#509]
ref 1caadab

After creating a few `MenuAdaptors` I realised that they all look the same, so I extracted it to a simple service with configuration. It’s much easier and much less boilerplate to add menu items this way:

```
kunstmaan_admin:
    menu_items:
      - route: AcmeBundle_foobaring_list
        label: FooBaring Module
        parent: KunstmaanAdminBundle_modules # this is optional
``` 

I’d like to hear your thoughts about this idea and I will soon prepare a PR. The current patch is just a POC, I haven’t even ran the code.

I think I could also create an annotation for it (but I don’t know if I can get route name for given action):
```php
class AcmeFooBaringController {
    /*
     * @Kunstmaan\Menu("FooBaring module", parent="…")
     */
    public function listAction() {}
}
```

Looking forward to your comments!
