### ISSUE TITLE
[KunstmaanSitemapBundle] sitemap.xml is empty for multilangual sites

### ISSUE THREAD

**Issue by evgemar** [Kunstmaan/KunstmaanBundlesCMS#618]
My sitemap for live site with a lot of pages

```xml
<?xml version="1.0" encoding="UTF-8"?>
<result>
  <entry>
    <entry><![CDATA[ru]]></entry>
    <entry><![CDATA[en]]></entry>
  </entry>
  <entry><![CDATA[http://domain]]></entry>
</result>
```

The routing is
```yml
# KunstmaanSitemapBundle
KunstmaanSitemapBundle:
    resource: "@KunstmaanSitemapBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/
    requirements:
        _locale: %requiredlocales%
```

Seems like the rule
> Once the bundle is installed, you will be able to view the generated sitemap XML on the '/en/sitemap.xml' route.

is not working
