### ISSUE TITLE
[FixtureBundle] PagePart translations do not seem to work properly

### ISSUE THREAD

**Issue by virtualize** [Kunstmaan/KunstmaanBundlesCMS#638]
Fixture Examples:

```
\App\SiteBundle\Entity\PageParts\HeaderPagePart:
    part_magazine_header:
        niv: 1
        parameters:
            page: @page_magazine
            context: main
        translations:
            en: { title: EN Title }
            de: { title: DE Titel }

\App\SiteBundle\Entity\PageParts\IntroPagePart:
    part_magazine_intro:
        parameters:
            page: @page_magazine
            context: intro
        translations: 
            de: { title: Magazin, abstract: DE }
            en: { title: Magazine, abstract: EN }
```

In both examples the first translation is used for all other languages. Same effect with more languages.
Is my syntax correct? Any hints would be appreciated.
