### ISSUE TITLE
Add Google Oauth integration

### ISSUE THREAD

**Issue by WardBrems** [Kunstmaan/KunstmaanBundlesCMS#806]
It would be very interesting to implement the google oauth functionality into the bundles.
Meaning you can login by just authenticating with your gmail address.

**Comment by mlebkowski** [comment]
It’s very simple to implement using: https://github.com/hwi/HWIOAuthBundle

Example:

# config.yml:
```
hwi_oauth:
    firewall_name: main
    resource_owners:
        google:
            type:          google
            client_id:     %google.api.client_id%
            client_secret: %google.api.client_secret%
            scope:         "email profile"
```

# routing.yml
```
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

google_login:
    path: /login/check-google

```

# security.yml
```
security:
    firewalls:
        main: 
            oauth:
                resource_owners:
                    google:             google_login
                login_path:        /admin/login
                use_forward:       true
                failure_path:      fos_user_registration_register

                oauth_user_provider:
                    service: acme.oauth.user_provider
```

Now just create `acme.oauth.user_provider` implementing `OAuthAwareUserProviderInterface` and you’re set. Anyway, dig deeper into the HWI documentation and it shouldn’t take you more than a few hours to set up.
